apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wnj32nli8-nodejs-gitops
  description: This is GitOps manifest for wnj32nli8-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=wnj32nli8-nodejs
    backstage.io/kubernetes-id: wnj32nli8-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: wnj32nli8-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wnj32nli8-nodejs
