apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wnj32nli8-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:11073fa5ae7343641489f9a8118ed0a9429d5f82@sha256:f80a878cc3b8b41c0dac4e22c0fa15534832cd1a24ddbf533573b717758f8bbc
          name: container-image
