apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wnj32nli8-nodejs
  janus-idp.io/tekton: wnj32nli8-nodejs
  backstage.io/kubernetes-id: wnj32nli8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wnj32nli8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
